algoritmo "Simular Reajuste Salarial"
// Função : Simular qual o valor do salário reajustado
// Autor : Nadir Baseggio
// Data : 23/02/2022
// Seção de Declarações 
var
Salario_atual, Salario_reajustado: real

inicio
Escreval("Informe o salario atual: ")
leia(Salario_atual)
Salario_reajustado <- salario_atual * 1.3
Escreval("Seu novo salário com reajuste de 30% será de: ",Salario_Reajustado)

fimalgoritmo
